// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PS3Larroque.Infrastructure;

#nullable disable

namespace PS3Larroque.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220142155_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PS3Larroque.Domain.Entities.Preventa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer")
                        .HasColumnName("sucursal_id");

                    b.Property<string>("Vendedor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendedor");

                    b.HasKey("Id");

                    b.ToTable("preventa", (string)null);
                });

            modelBuilder.Entity("PS3Larroque.Domain.Entities.PreventaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("MetodoPagoKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_unit");

                    b.Property<int>("PreventaId")
                        .HasColumnType("integer")
                        .HasColumnName("preventa_id");

                    b.HasKey("Id");

                    b.HasIndex("PreventaId");

                    b.ToTable("preventa_item", (string)null);
                });

            modelBuilder.Entity("ProductoLegacy", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Consola")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consola");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("PrecioCompraUsado")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_compra_usado");

                    b.Property<decimal>("PrecioVentaNuevo")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_venta_nuevo");

                    b.HasKey("Codigo");

                    b.ToTable("productos_legacy", (string)null);
                });

            modelBuilder.Entity("StockSucursal", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Sucursal")
                        .HasColumnType("text")
                        .HasColumnName("sucursal");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Consola")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consola");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Codigo", "Sucursal");

                    b.ToTable("stock_sucursal", (string)null);
                });

            modelBuilder.Entity("PS3Larroque.Domain.Entities.PreventaItem", b =>
                {
                    b.HasOne("PS3Larroque.Domain.Entities.Preventa", "Preventa")
                        .WithMany("Items")
                        .HasForeignKey("PreventaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preventa");
                });

            modelBuilder.Entity("PS3Larroque.Domain.Entities.Preventa", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
